services:
  # База данных
  postgres:
    image: postgres:16-alpine
    container_name: cassiopeia_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cassiopeia}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:7-alpine
    container_name: cassiopeia_redis
    ports:
      - "6379:6379"

  # Rust сервис
  rust_iss:
    build: ./services/rust-iss
    container_name: cassiopeia_rust
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/${POSTGRES_DB:-cassiopeia}
      REDIS_URL: redis://redis:6379
      NASA_API_KEY: ${NASA_API_KEY}
      NASA_API_URL: ${NASA_API_URL}
      WHERE_ISS_URL: ${WHERE_ISS_URL}
    ports:
      - "3000:3000"

  # PHP/Laravel
  php:
    build: ./services/php-web
    container_name: cassiopeia_php
    depends_on:
      - postgres
      - redis
      - rust_iss
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB:-cassiopeia}
      DB_USERNAME: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWST_HOST: ${JWST_HOST}
      JWST_API_KEY: ${JWST_API_KEY}
      JWST_EMAIL: ${JWST_EMAIL}
      ASTRO_APP_ID: ${ASTRO_APP_ID}
      ASTRO_APP_SECRET: ${ASTRO_APP_SECRET}
      RUST_BASE: http://rust_iss:3000
    volumes:
      - ./services/php-web:/var/www/html

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: cassiopeia_nginx
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ./services/php-web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/php-web:/var/www/html:ro

  # Pascal Legacy
  pascal_legacy:
    build: ./services/pascal-legacy
    container_name: cassiopeia_pascal
    depends_on:
      - postgres
    environment:
      GEN_PERIOD_SEC: ${PAS_LEGACY_PERIOD:-300}
      CSV_OUT_DIR: /data/csv
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      PGDATABASE: ${POSTGRES_DB:-cassiopeia}
    volumes:
      - ./data:/data