services:
  # PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: cassiopeia_db
    environment:
      POSTGRES_DB: cassiopeia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # PHP/Laravel (самый простой вариант)
  php:
    image: php:8.2-fpm-alpine
    container_name: cassiopeia_php
    depends_on:
      - db
    volumes:
      - ./services/php-web:/var/www/html

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: cassiopeia_nginx
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ./services/php-web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/php-web:/var/www/html:ro